name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  go_router: ^6.2.0
  shared_preferences: ^2.0.18
  provider: ^6.0.5
  oauth2: ^2.0.1
  dev: ^1.0.0
  mobx_codegen: ^2.1.1
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  http: ^0.13.5
  oauth2_client: ^3.2.1
  clash_bot_api:
    path: ../clash-bot-api
  animated_text_kit: ^4.2.2
  storybook_flutter: ^0.14.1
  validators: ^3.0.0
  retry: ^3.1.1
  stomp_dart_client: ^0.4.4
  collection: ^1.17.0
  flutter_animate: ^4.1.1+1
  uuid: ^3.0.7
  envied: ^1.1.1
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.1
  firebase_analytics: ^11.4.4
  firebase_analytics_web: ^0.5.10+10
  intl: ^0.18.1
  flutter_neat_and_clean_calendar: ^0.4.16
  flutter_svg: ^2.0.9
  clashbot_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.10.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true


assets:
  - ../assets/markdown/privacy-policy.md
  - ../images/TopIcon.webp
  - ../images/BotIcon.webp
  - ../images/MidIcon.webp
  - ../images/JGIcon.webp
  - ../images/SuppIcon.webp
  - ../svgs/ClashBot-HomePage.svg