// Mocks generated by Mockito 5.4.5 from annotations
// in clashbot_flutter/test/widget/clash_notification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:clash_bot_api/api.dart' as _i10;
import 'package:clashbot_flutter/models/clash_notification.dart' as _i9;
import 'package:clashbot_flutter/models/clashbot_user.dart' as _i4;
import 'package:clashbot_flutter/models/discord_guild.dart' as _i12;
import 'package:clashbot_flutter/models/discord_user.dart' as _i6;
import 'package:clashbot_flutter/stores/application_details.store.dart' as _i7;
import 'package:clashbot_flutter/stores/discord_details.store.dart' as _i2;
import 'package:clashbot_flutter/stores/riot_champion.store.dart' as _i3;
import 'package:mobx/mobx.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDiscordDetailsStore_0 extends _i1.SmartFake
    implements _i2.DiscordDetailsStore {
  _FakeDiscordDetailsStore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRiotChampionStore_1 extends _i1.SmartFake
    implements _i3.RiotChampionStore {
  _FakeRiotChampionStore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClashBotUser_2 extends _i1.SmartFake implements _i4.ClashBotUser {
  _FakeClashBotUser_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObservableList_3<T> extends _i1.SmartFake
    implements _i5.ObservableList<T> {
  _FakeObservableList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObservableMap_4<K, V> extends _i1.SmartFake
    implements _i5.ObservableMap<K, V> {
  _FakeObservableMap_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_5 extends _i1.SmartFake
    implements _i5.ReactiveContext {
  _FakeReactiveContext_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiscordUser_6 extends _i1.SmartFake implements _i6.DiscordUser {
  _FakeDiscordUser_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApplicationDetailsStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationDetailsStore extends _i1.Mock
    implements _i7.ApplicationDetailsStore {
  MockApplicationDetailsStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DiscordDetailsStore get discordDetailsStore => (super.noSuchMethod(
        Invocation.getter(#discordDetailsStore),
        returnValue: _FakeDiscordDetailsStore_0(
          this,
          Invocation.getter(#discordDetailsStore),
        ),
      ) as _i2.DiscordDetailsStore);

  @override
  set discordDetailsStore(_i2.DiscordDetailsStore? _discordDetailsStore) =>
      super.noSuchMethod(
        Invocation.setter(
          #discordDetailsStore,
          _discordDetailsStore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.RiotChampionStore get riotChampionStore => (super.noSuchMethod(
        Invocation.getter(#riotChampionStore),
        returnValue: _FakeRiotChampionStore_1(
          this,
          Invocation.getter(#riotChampionStore),
        ),
      ) as _i3.RiotChampionStore);

  @override
  set riotChampionStore(_i3.RiotChampionStore? _riotChampionStore) =>
      super.noSuchMethod(
        Invocation.setter(
          #riotChampionStore,
          _riotChampionStore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  set id(String? value) => super.noSuchMethod(
        Invocation.setter(
          #id,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ClashBotUser get clashBotUser => (super.noSuchMethod(
        Invocation.getter(#clashBotUser),
        returnValue: _FakeClashBotUser_2(
          this,
          Invocation.getter(#clashBotUser),
        ),
      ) as _i4.ClashBotUser);

  @override
  set clashBotUser(_i4.ClashBotUser? value) => super.noSuchMethod(
        Invocation.setter(
          #clashBotUser,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ObservableList<String> get preferredServers => (super.noSuchMethod(
        Invocation.getter(#preferredServers),
        returnValue: _FakeObservableList_3<String>(
          this,
          Invocation.getter(#preferredServers),
        ),
      ) as _i5.ObservableList<String>);

  @override
  set preferredServers(_i5.ObservableList<String>? value) => super.noSuchMethod(
        Invocation.setter(
          #preferredServers,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#error),
        ),
      ) as String);

  @override
  set error(String? value) => super.noSuchMethod(
        Invocation.setter(
          #error,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ObservableList<_i9.ClashNotification> get notifications =>
      (super.noSuchMethod(
        Invocation.getter(#notifications),
        returnValue: _FakeObservableList_3<_i9.ClashNotification>(
          this,
          Invocation.getter(#notifications),
        ),
      ) as _i5.ObservableList<_i9.ClashNotification>);

  @override
  set notifications(_i5.ObservableList<_i9.ClashNotification>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #notifications,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ObservableMap<String, _i10.Subscription> get subscription =>
      (super.noSuchMethod(
        Invocation.getter(#subscription),
        returnValue: _FakeObservableMap_4<String, _i10.Subscription>(
          this,
          Invocation.getter(#subscription),
        ),
      ) as _i5.ObservableMap<String, _i10.Subscription>);

  @override
  _i5.ObservableList<String> get sortedSelectedServers => (super.noSuchMethod(
        Invocation.getter(#sortedSelectedServers),
        returnValue: _FakeObservableList_3<String>(
          this,
          Invocation.getter(#sortedSelectedServers),
        ),
      ) as _i5.ObservableList<String>);

  @override
  List<_i9.ClashNotification> get sortedNotifications => (super.noSuchMethod(
        Invocation.getter(#sortedNotifications),
        returnValue: <_i9.ClashNotification>[],
      ) as List<_i9.ClashNotification>);

  @override
  List<_i9.ClashNotification> get unreadNotifications => (super.noSuchMethod(
        Invocation.getter(#unreadNotifications),
        returnValue: <_i9.ClashNotification>[],
      ) as List<_i9.ClashNotification>);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_5(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.ReactiveContext);

  @override
  _i11.Future<void> refreshSelectedServers() => (super.noSuchMethod(
        Invocation.method(
          #refreshSelectedServers,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> refreshClashBotUser() => (super.noSuchMethod(
        Invocation.method(
          #refreshClashBotUser,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void triggerError(String? errorMessage) => super.noSuchMethod(
        Invocation.method(
          #triggerError,
          [errorMessage],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUser(_i9.ClashNotification? clashNotification) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyUser,
          [clashNotification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void readNotification(String? uuid) => super.noSuchMethod(
        Invocation.method(
          #readNotification,
          [uuid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeFromServer(String? serverId) => super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromServer,
          [serverId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribeToServer(String? serverId) => super.noSuchMethod(
        Invocation.method(
          #subscribeToServer,
          [serverId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> loadUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #loadUserDetails,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i4.ClashBotUser> createUser(
    String? defaultServerId,
    List<String>? selectedServersToUse,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            defaultServerId,
            selectedServersToUse,
          ],
        ),
        returnValue: _i11.Future<_i4.ClashBotUser>.value(_FakeClashBotUser_2(
          this,
          Invocation.method(
            #createUser,
            [
              defaultServerId,
              selectedServersToUse,
            ],
          ),
        )),
      ) as _i11.Future<_i4.ClashBotUser>);
}

/// A class which mocks [DiscordDetailsStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscordDetailsStore extends _i1.Mock
    implements _i2.DiscordDetailsStore {
  MockDiscordDetailsStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.DiscordUser get discordUser => (super.noSuchMethod(
        Invocation.getter(#discordUser),
        returnValue: _FakeDiscordUser_6(
          this,
          Invocation.getter(#discordUser),
        ),
      ) as _i6.DiscordUser);

  @override
  set discordUser(_i6.DiscordUser? value) => super.noSuchMethod(
        Invocation.setter(
          #discordUser,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ObservableList<_i12.DiscordGuild> get discordGuilds =>
      (super.noSuchMethod(
        Invocation.getter(#discordGuilds),
        returnValue: _FakeObservableList_3<_i12.DiscordGuild>(
          this,
          Invocation.getter(#discordGuilds),
        ),
      ) as _i5.ObservableList<_i12.DiscordGuild>);

  @override
  set discordGuilds(_i5.ObservableList<_i12.DiscordGuild>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #discordGuilds,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ObservableMap<String, String> get discordIdToName => (super.noSuchMethod(
        Invocation.getter(#discordIdToName),
        returnValue: _FakeObservableMap_4<String, String>(
          this,
          Invocation.getter(#discordIdToName),
        ),
      ) as _i5.ObservableMap<String, String>);

  @override
  set discordIdToName(_i5.ObservableMap<String, String>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #discordIdToName,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#status),
        ),
      ) as String);

  @override
  set status(String? value) => super.noSuchMethod(
        Invocation.setter(
          #status,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get detailsLoaded => (super.noSuchMethod(
        Invocation.getter(#detailsLoaded),
        returnValue: false,
      ) as bool);

  @override
  bool get guildDetailsLoaded => (super.noSuchMethod(
        Invocation.getter(#guildDetailsLoaded),
        returnValue: false,
      ) as bool);

  @override
  Map<String, _i12.DiscordGuild> get discordGuildMap => (super.noSuchMethod(
        Invocation.getter(#discordGuildMap),
        returnValue: <String, _i12.DiscordGuild>{},
      ) as Map<String, _i12.DiscordGuild>);

  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_5(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.ReactiveContext);

  @override
  _i11.Future<_i6.DiscordUser> fetchUserDetails(String? discordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserDetails,
          [discordId],
        ),
        returnValue: _i11.Future<_i6.DiscordUser>.value(_FakeDiscordUser_6(
          this,
          Invocation.method(
            #fetchUserDetails,
            [discordId],
          ),
        )),
      ) as _i11.Future<_i6.DiscordUser>);

  @override
  _i11.Future<void> fetchCurrentUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentUserDetails,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> fetchUserGuilds() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserGuilds,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> loadEverything() => (super.noSuchMethod(
        Invocation.method(
          #loadEverything,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
