import 'dart:io';

void main() {
  try {
    var commitDetails = '';
    // Run git commands
    final tagName =
        Process.runSync('git', ['describe', '--tags', '--exact-match'])
            .stdout
            .trim();
    if (tagName.isNotEmpty) {
      commitDetails = tagName;
    } else {
      final commitHash = Process.runSync('git', ['rev-parse', 'HEAD'])
          .stdout
          .trim()
          .substring(0, 6);
      final branchName =
          Process.runSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'])
              .stdout
              .trim();
      final trimmedBranchName = branchName.length > 5
          ? branchName.substring(branchName.length - 5)
          : branchName;
      commitDetails = '$trimmedBranchName:$commitHash';
    }

    // Create a Dart file with the details
    final content = '''
// This file is automatically generated. Do not modify manually.
class GitInfo {
  static const String commitDetails = '$commitDetails';
}
''';

    final outputFile = File('lib/generated/git_info.dart');
    outputFile.writeAsStringSync(content);
    print('# Generated Git info');
    print('| Details |');
    print('|------------|');
    print('| $commitDetails |');
  } catch (e) {
    print('Error generating Git info: $e');
  }
}
