import 'dart:io';

void main() {
  try {
    // Run git commands
    final commitHash = Process.runSync('git', ['rev-parse', 'HEAD'])
        .stdout
        .trim()
        .substring(0, 6);
    final branchName =
        Process.runSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'])
            .stdout
            .trim();

    // Create a Dart file with the details
    final content = '''
// This file is automatically generated. Do not modify manually.
class GitInfo {
  static const String commitHash = '$commitHash';
  static const String branchName = '$branchName';
}
''';

    final outputFile = File('lib/generated/git_info.dart');
    outputFile.writeAsStringSync(content);
    print('Git info generated successfully.');
  } catch (e) {
    print('Error generating Git info: $e');
  }
}
