name: Clash Bot Flutter UI - Pull Request

on:
  pull_request:
      branches:
          - main
      paths-ignore:
          - '**/README.md'
          - '**/.gitignore'

env:
  FLUTTER_VERSION: '3.29.0'

jobs:
  unit:
      name: Run Tests
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4.2.2

        - uses: subosito/flutter-action@v2.18.0
          with:
              flutter-version: ${{ env.FLUTTER_VERSION }}
              channel: 'stable'

        - name: Check Flutter version
          run: flutter --version

        - name: Download Dependencies
          run: flutter pub get

        - name: Create environment file          
          env:
            CLASHBOT_SERVICE_URL: http://localhost:8080/api/v2
            MOCK_DISCORD_SERVICE: false
          run: \./ciScripts/build-env-file\.sh CLASHBOT_SERVICE_URL ${CLASHBOT_SERVICE_URL} MOCK_DISCORD_SERVICE ${MOCK_DISCORD_SERVICE}

        - name: Unit Tests
          run: flutter test "test/unit/" >> $GITHUB_STEP_SUMMARY

  golden:
      name: Run Golden File tests
      runs-on: macos-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4.2.2

        - uses: subosito/flutter-action@v2.18.0
          with:
              flutter-version: ${{ env.FLUTTER_VERSION }}
              channel: 'stable'

        - name: Check Flutter version
          run: flutter --version

        - name: Download Dependencies
          run: flutter pub get

        - name: Create environment file          
          env:
            CLASHBOT_SERVICE_URL: http://localhost:8080/api/v2
            MOCK_DISCORD_SERVICE: false
          run: \./ciScripts/build-env-file\.sh CLASHBOT_SERVICE_URL ${CLASHBOT_SERVICE_URL} MOCK_DISCORD_SERVICE ${MOCK_DISCORD_SERVICE}

        - name: Generate Envied Files
          run: flutter pub run build_runner build --delete-conflicting-outputs  --define=envied_generator:envied=path=env.prod

        - name: Golden Tests
          run: flutter test "test/widget/" >> $GITHUB_STEP_SUMMARY

        - name: Publish Test Golden Test Failures
          if: ${{ failure() }}
          uses: actions/upload-artifact@v4.6.1
          with:
            name: golden-failures
            path: test/widget/failures
  
  build:
    name: Build web package
    needs:
      - unit
      - golden 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - uses: subosito/flutter-action@v2.18.0
        with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'

      - name: Check Flutter version
        run: flutter --version

      - name: Create environment file          
        env:
          CLASHBOT_SERVICE_URL: http://localhost:8080/api/v2
          MOCK_DISCORD_SERVICE: false
        run: \./ciScripts/build-env-file\.sh CLASHBOT_SERVICE_URL ${CLASHBOT_SERVICE_URL} MOCK_DISCORD_SERVICE ${MOCK_DISCORD_SERVICE}

      - name: Build Web Bundle
        run: flutter build web >> $GITHUB_STEP_SUMMARY