name: Clash Bot Flutter UI - Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.29.0'

jobs:
  build:
      name: Build Flutter UI
      runs-on: ubuntu-latest
      environment: Production
  
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4.2.2

        - uses: subosito/flutter-action@v2.18.0
          with:
              flutter-version: ${{ env.FLUTTER_VERSION }}
              channel: 'stable'

        - name: Check Flutter version
          run: flutter --version

        - name: Download Dependencies
          run: flutter pub get

        - name: Create environment file          
          env:
            CLASHBOT_SERVICE_URL: ${{ vars.CLASHBOT_SERVICE_URL }}
            MOCK_DISCORD_SERVICE: false
            DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
          run: ./ciScripts/build-env-file.sh CLASHBOT_SERVICE_URL ${CLASHBOT_SERVICE_URL} MOCK_DISCORD_SERVICE ${MOCK_DISCORD_SERVICE} discordClientId ${DISCORD_CLIENT_ID} clashbotEventUrl http://localhost:8000/ws

        - name: Generate Envied Files
          run: |
            dart run build_runner clean
            dart scripts/generate_git_info.dart >> $GITHUB_STEP_SUMMARY
            dart run build_runner build --delete-conflicting-outputs

        - name: Print generated environment file
          run: cat ./lib/core/config/env.g.dart

        - name: Build Web Bundle
          run: flutter build web --release

        - name: Archive Web Bundle
          uses: actions/upload-artifact@v4.6.1
          with:
            name: web-bundle
            path: build/web/**

  deployment:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: 
      - build
    environment: 
      name: Production
      url: ${{ steps.change-page-url.outputs.new_page_url }}
    permissions:
      id-token: write

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ARN }}
          aws-region: us-east-1

      - name: Download web bundle
        uses: actions/download-artifact@v4.1.9
        with:
          name: web-bundle
          path: web

      - name: Remove old files from S3
        run: aws s3 rm s3://${{ secrets.S3_BUCKET }} --recursive

      - name: Push to s3
        run: aws s3 cp web/ s3://${{ secrets.S3_BUCKET }} --recursive

      - name: Change Page Url
        id: change-page-url
        run: echo "name=new_page_url::https://clash-bot.ninja" >> $GITHUB_OUTPUT
