name: Clash Bot Flutter UI - Release

on:
  push:
    tags:
      - 'v*'

env:
  FLUTTER_VERSION: '3.29.0'

jobs:
  build:
      name: Build Flutter UI
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4.2.2

        - uses: subosito/flutter-action@v2.18.0
          with:
              flutter-version: ${{ env.FLUTTER_VERSION }}
              channel: 'stable'

        - name: Check Flutter version
          run: flutter --version

        - name: Download Dependencies
          run: flutter pub get

        - name: Set environment variables
          run: |
            ./pre_build.sh prod
            ./build.sh prod
            ls -lha .env

        - name: Generate Envied Files
          run: flutter pub run build_runner build --delete-conflicting-outputs

        - name: Build Web Bundle
          run: flutter build web

        - name: Archive Web Bundle
          uses: actions/upload-artifact@v4.6.1
          with:
            name: web-bundle
            path: build/web/**

  deployment:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: 
      - build
    environment: Production
    permissions:
      id-token: write 

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ARN }}
          aws-region: us-east-1

      - name: Download web bundle
        uses: actions/download-artifact@v4.1.9
        with:
          name: web-bundle
          path: web

      - name: Remove old files from S3
        run: aws s3 rm s3://${{ secrets.S3_BUCKET }} --recursive

      - name: Push to s3
        run: aws s3 cp web/ s3://${{ secrets.S3_BUCKET }} --recursive
